import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsInt, IsISO8601, IsOptional, IsString, IsUUID, Max, MaxLength, Min, MinLength } from 'class-validator';
import { EnrollmentStatus, TrainingKind, TrainingStatus } from '@prisma/client';
import { PaginationQueryDto } from '../../../common/dto/pagination.dto';

export class TrainingQueryDto extends PaginationQueryDto { @ApiPropertyOptional({ enum: TrainingKind }) @IsOptional() @IsEnum(TrainingKind) kind?: TrainingKind; @ApiPropertyOptional() @IsOptional() @IsBoolean() isMandatory?: boolean; }
export class CreateTrainingDto { @ApiProperty() @IsString() @MinLength(2) @MaxLength(50) code!: string; @ApiProperty() @IsString() @MinLength(2) @MaxLength(180) title!: string; @ApiPropertyOptional({ enum: TrainingKind }) @IsOptional() @IsEnum(TrainingKind) kind?: TrainingKind; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(10000) description?: string; @ApiPropertyOptional() @IsOptional() @IsBoolean() isMandatory?: boolean; @ApiPropertyOptional({ default: 100 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) passingScore?: number; @ApiPropertyOptional() @IsOptional() @IsISO8601() availableFrom?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() availableTo?: string; }
export class UpdateTrainingDto extends CreateTrainingDto {}
export class CreateTrainingModuleDto { @ApiProperty() @IsString() @MinLength(2) @MaxLength(180) title!: string; @ApiProperty() @IsString() @MaxLength(30) contentType!: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(10000) contentBody?: string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1000) contentUrl?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) durationMinutes?: number; @ApiPropertyOptional({ default: true }) @IsOptional() @IsBoolean() isRequired?: boolean; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) position?: number; }
export class EnrollTrainingDto { @ApiProperty() @IsUUID() trainingId!: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() dueAt?: string; }
export class BulkEnrollDto { @ApiProperty() @IsUUID() trainingId!: string; @ApiProperty({ type: [String] }) @IsUUID(undefined, { each: true }) pastorIds!: string[]; }
export class ProgressDto { @ApiProperty() @IsUUID() moduleId!: string; @ApiProperty() @IsBoolean() completed!: boolean; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) secondsSpent?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) lastPositionSec?: number; }
export class EnrollmentQueryDto extends PaginationQueryDto { @ApiPropertyOptional() @IsOptional() @IsUUID() trainingId?: string; @ApiPropertyOptional() @IsOptional() @IsUUID() pastorId?: string; @ApiPropertyOptional({ enum: EnrollmentStatus }) @IsOptional() @IsEnum(EnrollmentStatus) status?: EnrollmentStatus; }
