import { Injectable } from '@nestjs/common';
import { AuditAction, EnrollmentStatus, Prisma, TrainingStatus } from '@prisma/client';
import { PageDto } from '../../common/dto/pagination.dto';
import { AppError } from '../../common/errors/app-error';
import { randomToken } from '../../common/utils/crypto.util';
import { PrismaService } from '../../infra/prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { AccessControlService } from '../authorization/access-control.service';
import { PERMISSIONS } from '../authorization/permissions.constants';
import type { AuthenticatedUser } from '../authorization/authorization.types';
import { NotificationsService } from '../notifications/notifications.service';
import { BulkEnrollDto, CreateTrainingDto, CreateTrainingModuleDto, EnrollTrainingDto, EnrollmentQueryDto, ProgressDto, TrainingQueryDto, UpdateTrainingDto } from './dto/training.dto';

@Injectable()
export class TrainingService {
  constructor(private readonly prisma: PrismaService, private readonly acl: AccessControlService, private readonly audit: AuditService, private readonly notifications: NotificationsService) {}

  async catalog(user: AuthenticatedUser, query: TrainingQueryDto) {
    const now = new Date();
    const where: Prisma.TrainingWhereInput = { deletedAt: null, status: TrainingStatus.PUBLISHED, AND: [{ OR: [{ availableFrom: null }, { availableFrom: { lte: now } }] }, { OR: [{ availableTo: null }, { availableTo: { gte: now } }] }], ...(query.kind ? { kind: query.kind } : {}), ...(query.isMandatory !== undefined ? { isMandatory: query.isMandatory } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' } }, { code: { contains: query.search, mode: 'insensitive' } }] } : {}) };
    const [total, rows] = await this.prisma.$transaction([this.prisma.training.count({ where }), this.prisma.training.findMany({ where, orderBy: { title: 'asc' }, skip: query.skip, take: query.take, include: { _count: { select: { modules: true } }, enrollments: user.pastorId ? { where: { pastorId: user.pastorId }, select: { id: true, status: true, progressPct: true, dueAt: true, completedAt: true } } : false } })]);
    return PageDto.of(rows.map((row) => ({ ...row, enrollment: row.enrollments[0] ?? null, enrollments: undefined })), total, query);
  }

  async get(user: AuthenticatedUser, id: string) {
    const training = await this.prisma.training.findFirst({ where: { id, deletedAt: null }, include: { modules: { orderBy: { position: 'asc' }, select: { id: true, title: true, description: true, contentType: true, contentUrl: true, contentBody: true, durationMinutes: true, position: true, isRequired: true } }, enrollments: user.pastorId ? { where: { pastorId: user.pastorId }, select: { id: true, status: true, progressPct: true, enrolledAt: true, startedAt: true, completedAt: true, dueAt: true, score: true, progress: { select: { moduleId: true, completed: true } } } } : false } });
    if (!training) throw AppError.notFound('Treinamento nao encontrado.');
    const enrolled = training.enrollments.length > 0;
    // `enrollment` (singular) e a matricula de quem consulta - mesmo nome usado no catalogo.
    if (!enrolled && training.status !== TrainingStatus.PUBLISHED) return { ...training, modules: training.modules.map(({ contentBody: _, contentUrl: __, ...module }) => module), enrollments: undefined, enrollment: null };
    return { ...training, enrollments: undefined, enrollment: training.enrollments[0] ?? null };
  }

  async create(user: AuthenticatedUser, dto: CreateTrainingDto) { this.acl.assert(user, PERMISSIONS.TRAINING_WRITE); const training = await this.prisma.training.create({ data: { code: dto.code.trim().toUpperCase(), title: dto.title.trim(), kind: dto.kind, description: dto.description, isMandatory: dto.isMandatory, passingScore: dto.passingScore, availableFrom: dto.availableFrom ? new Date(dto.availableFrom) : undefined, availableTo: dto.availableTo ? new Date(dto.availableTo) : undefined } }); await this.audit.record({ userId: user.id, action: AuditAction.CREATE, entity: 'Training', entityId: training.id }); return training; }
  async update(user: AuthenticatedUser, id: string, dto: UpdateTrainingDto) { this.acl.assert(user, PERMISSIONS.TRAINING_WRITE); const training = await this.prisma.training.update({ where: { id }, data: { code: dto.code.trim().toUpperCase(), title: dto.title.trim(), kind: dto.kind, description: dto.description, isMandatory: dto.isMandatory, passingScore: dto.passingScore, availableFrom: dto.availableFrom ? new Date(dto.availableFrom) : undefined, availableTo: dto.availableTo ? new Date(dto.availableTo) : undefined } }); await this.audit.record({ userId: user.id, action: AuditAction.UPDATE, entity: 'Training', entityId: id }); return training; }
  async publish(user: AuthenticatedUser, id: string) { this.acl.assert(user, PERMISSIONS.TRAINING_WRITE); return this.prisma.training.update({ where: { id }, data: { status: TrainingStatus.PUBLISHED } }); }
  async addModule(user: AuthenticatedUser, trainingId: string, dto: CreateTrainingModuleDto) { this.acl.assert(user, PERMISSIONS.TRAINING_WRITE); const last = await this.prisma.trainingModule.aggregate({ where: { trainingId }, _max: { position: true } }); return this.prisma.trainingModule.create({ data: { trainingId, title: dto.title.trim(), contentType: dto.contentType, contentBody: dto.contentBody, contentUrl: dto.contentUrl, durationMinutes: dto.durationMinutes, isRequired: dto.isRequired, position: dto.position ?? ((last._max.position ?? 0) + 1) } }); }
  async enroll(user: AuthenticatedUser, dto: EnrollTrainingDto) { this.acl.assert(user, PERMISSIONS.TRAINING_ENROLL); if (!user.pastorId) throw AppError.validation('Usuario sem pastor vinculado.'); const training = await this.prisma.training.findFirst({ where: { id: dto.trainingId, status: TrainingStatus.PUBLISHED }, select: { id: true, title: true } }); if (!training) throw AppError.notFound('Treinamento nao encontrado.'); const enrollment = await this.prisma.trainingEnrollment.upsert({ where: { trainingId_pastorId: { trainingId: dto.trainingId, pastorId: user.pastorId } }, create: { trainingId: dto.trainingId, pastorId: user.pastorId, dueAt: dto.dueAt ? new Date(dto.dueAt) : undefined }, update: {}, include: { training: true } }); await this.notifications.create({ userId: user.id, type: 'TRAINING', title: 'Matricula realizada', body: `Voce foi matriculado em ${training.title}.`, link: `/training/${training.id}`, entity: 'Training', entityId: training.id }); return enrollment; }
  async bulkEnroll(user: AuthenticatedUser, dto: BulkEnrollDto) { this.acl.assert(user, PERMISSIONS.TRAINING_MANAGE_ENROLLMENTS); await this.prisma.training.findUniqueOrThrow({ where: { id: dto.trainingId } }); for (const pastorId of dto.pastorIds) await this.acl.assertPastorAccess(user, pastorId, PERMISSIONS.TRAINING_MANAGE_ENROLLMENTS); return this.prisma.trainingEnrollment.createMany({ data: dto.pastorIds.map((pastorId) => ({ trainingId: dto.trainingId, pastorId })), skipDuplicates: true }); }
  async enrollments(user: AuthenticatedUser, query: EnrollmentQueryDto) { const scope = await this.acl.pastorWhere(user, PERMISSIONS.TRAINING_READ); const where: Prisma.TrainingEnrollmentWhereInput = { pastor: { is: scope }, ...(query.trainingId ? { trainingId: query.trainingId } : {}), ...(query.pastorId ? { pastorId: query.pastorId } : {}), ...(query.status ? { status: query.status } : {}) }; const [total, data] = await this.prisma.$transaction([this.prisma.trainingEnrollment.count({ where }), this.prisma.trainingEnrollment.findMany({ where, orderBy: { updatedAt: 'desc' }, skip: query.skip, take: query.take, include: { training: { select: { id: true, title: true } }, pastor: { select: { id: true, pastoralName: true } } } })]); return PageDto.of(data, total, query); }
  async progress(user: AuthenticatedUser, enrollmentId: string, dto: ProgressDto) { const enrollment = await this.prisma.trainingEnrollment.findUnique({ where: { id: enrollmentId }, include: { training: { include: { modules: true } } }, }); if (!enrollment) throw AppError.notFound('Matricula nao encontrada.'); if (enrollment.pastorId !== user.pastorId && !this.acl.has(user, PERMISSIONS.TRAINING_MANAGE_ENROLLMENTS)) throw AppError.forbidden(); const module = enrollment.training.modules.find((item) => item.id === dto.moduleId); if (!module) throw AppError.validation('Modulo nao pertence ao treinamento.'); const required = enrollment.training.modules.filter((item) => item.isRequired); const updated = await this.prisma.$transaction(async (tx) => { await tx.trainingProgress.upsert({ where: { enrollmentId_moduleId: { enrollmentId, moduleId: dto.moduleId } }, create: { enrollmentId, moduleId: dto.moduleId, completed: dto.completed, completedAt: dto.completed ? new Date() : null, secondsSpent: dto.secondsSpent ?? 0, lastPositionSec: dto.lastPositionSec ?? 0 }, update: { completed: dto.completed, completedAt: dto.completed ? new Date() : null, secondsSpent: dto.secondsSpent, lastPositionSec: dto.lastPositionSec } }); const completed = await tx.trainingProgress.count({ where: { enrollmentId, completed: true, moduleId: { in: required.map((item) => item.id) } } }); const pct = required.length ? Math.round((completed / required.length) * 100) : 100; return tx.trainingEnrollment.update({ where: { id: enrollmentId }, data: { progressPct: pct, status: pct >= enrollment.training.passingScore ? EnrollmentStatus.COMPLETED : EnrollmentStatus.IN_PROGRESS, startedAt: enrollment.startedAt ?? new Date(), completedAt: pct >= enrollment.training.passingScore ? new Date() : null, certificate: pct >= enrollment.training.passingScore ? { upsert: { create: { number: `CERT-${new Date().getFullYear()}-${Math.floor(Math.random() * 1_000_000).toString().padStart(6, '0')}`, verificationToken: randomToken(24) }, update: {} } } : undefined } }); }); return updated; }
  async summary(user: AuthenticatedUser, pastorId: string) { await this.acl.assertPastorAccess(user, pastorId, PERMISSIONS.TRAINING_READ); const rows = await this.prisma.trainingEnrollment.findMany({ where: { pastorId }, select: { status: true, progressPct: true } }); const total = rows.length; const completed = rows.filter((row) => row.status === EnrollmentStatus.COMPLETED).length; const inProgress = rows.filter((row) => row.status === EnrollmentStatus.IN_PROGRESS).length; return { total, completed, inProgress, pending: total - completed - inProgress, overallProgressPct: total ? Math.round(rows.reduce((sum, row) => sum + row.progressPct, 0) / total) : 0 }; }
  verify(token: string) { return this.prisma.certificate.findUnique({ where: { verificationToken: token }, include: { enrollment: { include: { training: { select: { title: true } }, pastor: { select: { pastoralName: true } } } } } }).then((certificate) => certificate ? { valid: true, number: certificate.number, trainingTitle: certificate.enrollment.training.title, pastoralName: certificate.enrollment.pastor.pastoralName, issuedAt: certificate.issuedAt } : { valid: false }); }
}
